---
labels:
  container: other
  owner: other
  dataset: other
rules:
  - pattern: ^(?P<container>argo-artifacts|container-logs|mimir-blocks|elasticsearch-snapshots)/
  - pattern: ^(?P<container>[^/]+)/(?P<owner>[^/]+)/(?P<dataset>[^/]+)
